### ISSUE TITLE
Create icon set

### ISSUE THREAD

**Issue by sphasse** [Sector67/nsa-away#15]
We need a non-default icon set

**Comment by erinzm** [comment]
So we need to replace the "little green android". Do any other icons need to be replaced?

**Comment by erinzm** [comment]
92938b52d32e3af0c480da93334b1c34ac46ae4f adds an icon, but it's not done (_yet_).

**Comment by erinzm** [comment]
e0545dd89a443c1eb2e0cf6e6a796245f5cf596b adds a _way better icon_!

**Comment by erinzm** [comment]
Here are some screenshots from my Nexus 10 of the new icon (in-app and on launcher):
![nsaaway-icon-onlauncher-cropped-v2](https://cloud.githubusercontent.com/assets/4635721/4293575/863fe144-3dd7-11e4-829d-f09a90ba627a.png)

![nsaaway-icon-inapp-cropped-v2](https://cloud.githubusercontent.com/assets/4635721/4293576/881cad08-3dd7-11e4-96e9-47a410b86a8f.png)

How do you like them @sphasse @pnovotnak @nmeronek @bobbaddeley?

**Comment by erinzm** [comment]
Closing this if no one objects.
