### ISSUE TITLE
Changing orientation re-encrypts and uses more keys

### ISSUE THREAD

**Issue by sphasse** [Sector67/nsa-away#23]
Currently changing the orientation on the display ciphertext page results in the message being re-encrypted and more key bytes being used.

**Comment by erinzm** [comment]
AsyncTasks are [one way](http://stackoverflow.com/questions/20514926/best-practice-to-handle-orientation-change-android) to do this, you can also override `onConfigurationChange` (which seems slightly wrong) as [here](http://jnastase.alner.net/archive/2010/10/27/handling-orientation-change-in-android.aspx).

We could also simply lock the orientation to vertical on everything, with the way we have it laid out, it'll look weird in landscape on small(er) screens.

**Comment by sphasse** [comment]
I am thinking a better way to resolve this will be to do the encryption in the sending page.  That way the plaintext never needs to be sent in the context across pages unless we want it for some other reason.  Encrypting once and displaying as many times as needed should allow us to handle orientation changes.
