### ISSUE TITLE
OTP decrypter?

### ISSUE THREAD

**Issue by ghost** [Sector67/nsa-away#25]
I'm looking to make a script to automate decrypting the math with the key. I've given this a couple tries after contributing to https://github.com/Andrew415/otp-gen but haven't been able to figure out how to do it on strings, maybe you guys could get it working?

**Comment by sphasse** [comment]
Sorry, I'm not sure I understand what you are asking for.  We handle all strings as UTF-8 and encrypt byte-wise.  The standalone Java otp library should let you automate encryption and decryption fairly easily.

**Comment by ghost** [comment]
What I want is to take any OTP string and key and print the message.

**Comment by sphasse** [comment]
The unit tests for our standalone one-time-pad-library library should provide good usage examples.  For example:

https://github.com/Sector67/one-time-pad-library-tests/blob/master/src/org/sector67/otp/test/FileKeyStoreTests.java
