### ISSUE TITLE
Implement simple USB sending capability

### ISSUE THREAD

**Issue by sphasse** [Sector67/nsa-away#29]
As a lead-in step to the keystroke sending function

**Comment by erinzm** [comment]
@sphasse Any specific libs/ strategies for doing this that you've found?

**Comment by sphasse** [comment]
My initial thought for a prototype was to communicate from the Android device to an Arduino using the Android as a USB host and a USB OTG (on the go) cable.  I got two of these cables and bread-boarded an Arduino up before frustratingly realizing that my Android device (a Samsung Galaxy Tab 4 7") does not support USB OTG.  There is already a compatibly-licensed implementation of a pure Java driver for communicating from Android to Arduino via USB OTG:

https://github.com/mik3y/usb-serial-for-android

Once basic Arduino communication was working, I have a separate USB UART that I would use for communication to the Anrdroid device, and then my plan was to configure the main Ardunio's USB to perform the HID functionality (https://github.com/ddiakopoulos/hiduino), with the separate USB adapter wired to I/O pins (e.g. http://arduino.cc/en/Main/MiniUSB) and communicating via software serial (http://arduino.cc/en/Reference/SoftwareSerial) to the Android device.  

That is an awful lot of moving parts for a prototype and the design would not necessarily implement the one-way send only guarantee (although something could be done to ensure one-way communication from the separate UART to the Arduino, perhaps as simple as no TX connection as a first cut).  But, that was my original plan.  I'm certainly interested in feedback and potential alternative approaches.

Scott

**Comment by erinzm** [comment]
Couldn't the Android phone just act as the HID?

**Comment by sphasse** [comment]
That would also work, but currently requires a custom kernel (http://stackoverflow.com/questions/4886833/android-usb-hid-device) or .  Probably not a bad tradeoff for a prototype, but hard to share.

**Comment by erinzm** [comment]
I think V-USB has better HID support, HIDuino was designed for USB midi
controllers.

**Comment by erinzm** [comment]
@sphasse My first thought was this: <pre>Phone ==> ATmega32U4 { LUFA CDC USB --> V-USB HID keyboard emulator } ==> Computer</pre>
That would be pretty simple to do at the code jam if anyone has a Leonardo or other ATmega32U4 based arduino.

**Comment by erinzm** [comment]
Or just a FTDI chip will work...

**Comment by erinzm** [comment]
I did this, but we're using something else. Closed

**Comment by erinzm** [comment]
We're now using USB HID again, so I'm reopening this.

**Comment by erinzm** [comment]
@nmeronek I'm assigning you, if you don't mind?

**Comment by erinzm** [comment]
Finished by @nmeronek. Not commited yet.
