### ISSUE TITLE
nsa-away not in sync with the OTP library repo

### ISSUE THREAD

**Issue by erinzm** [Sector67/nsa-away#34]
When I compile the latest nsa-away with the latest OTP lib (from Git), I get a bunch of incorrect method signatures and broken imports. Do you guys have a later version of the OTP lib on your computers that hasn't been uploaded yet? Or am I just doing something wrong? :blush:
Here's a picture of the error:
![nsaaway-errors-desync](https://cloud.githubusercontent.com/assets/4635721/4100693/73ae4d1a-30ab-11e4-93ef-836053fd7412.png)

Liam

**Comment by sphasse** [comment]
If you "git pull origin" to update your one-time-pad-library project you
should get those changes.  They were pushed a while back but I didn't make
it clear in the nsa-away project that an update of the one-time-pad-library
was also needed.  You'll probably want to grab the latest
oe-time-pad-library-tests as well.

Hope that helps, let me know if not.

Scott

On Sat, Aug 30, 2014 at 8:10 PM, Liam M notifications@github.com wrote:

> When I compile the latest nsa-away with the latest OTP lib (from Git), I
> get a bunch of incorrect method signatures and broken imports. Do you guys
> have a later version of the OTP lib on your computers that hasn't been
> uploaded yet? Or am I just doing something wrong? [image: :blush:]
> Here's a picture of the error:
> [image: nsaaway-errors-desync]
> https://cloud.githubusercontent.com/assets/4635721/4100693/73ae4d1a-30ab-11e4-93ef-836053fd7412.png
> 
> Liam
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Sector67/nsa-away/issues/34.

## 

 http://flexion.us
 Scott Hasse
Partner & CTO
_T._ 866-620-4353 _C._ 608-206-1813
_E._ shasse@flexion.us
 FLEXION - VALUE FORWARD
1500 West Main Street, Suite 500
Sun Prairie, WI 53590
 https://www.facebook.com/pages/Flexion/261352600607280
http://twitter.com/#!/flexion1
https://plus.google.com/u/0/117487668359646793321/posts

## 

---

_Notice_: The information contained in this message or any attached 
document is confidential and intended only for individuals to whom it is 
addressed. If you got this message in error, please inform me immediately 
using one of the methods above. In some cases, I may ask you to return the 
documents at my expense. In general, please simply destroy the information 
at once. Any unauthorized use, distribution, or copying of this information 
is prohibited.

**Comment by erinzm** [comment]
I just `git clone`d everything new, I don't think anything funny's going
on... but let me try...

**Comment by erinzm** [comment]
Nope, it _wasn't git_. Turns out Eclipse was caching code, and I just
deleted everything and started over because it was stale.
Eclipse is... different :smiley:

Thanks,
Liam

**Comment by erinzm** [comment]
Closed.

**Comment by erinzm** [comment]
Yeah, thanks again @sphasse for the help. Now `com.googlecode.tesseract.android.TessBaseAPI` is failing to be imported in **nsa-away**. I have all the latest, do I need to download and install other jars?

**Comment by sphasse** [comment]
Yes, as Tesseract is a native project you'll need to follow the
instructions to build it and import it as a library project.  There is
already a (probably unresolved right now in your environment) reference to
the tess-two project as a library project in the nsa-away project (in
eclipse, project->properties->Android) that might need to be changed
depending on the platform you are running on.  The tess-two build
instructions can be found at https://github.com/rmtheis/tess-two, but let
me know if you have any issues.

On Sat, Aug 30, 2014 at 8:45 PM, Liam M notifications@github.com wrote:

> Yeah, thanks again @sphasse https://github.com/sphasse for the help.
> Now com.googlecode.tesseract.android.TessBaseAPI is failing to be
> imported in _nsa-away_. I have all the latest, do I need to download and
> install other jars?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Sector67/nsa-away/issues/34#issuecomment-53975695.

## 

 http://flexion.us
 Scott Hasse
Partner & CTO
_T._ 866-620-4353 _C._ 608-206-1813
_E._ shasse@flexion.us
 FLEXION - VALUE FORWARD
1500 West Main Street, Suite 500
Sun Prairie, WI 53590
 https://www.facebook.com/pages/Flexion/261352600607280
http://twitter.com/#!/flexion1
https://plus.google.com/u/0/117487668359646793321/posts

## 

---

_Notice_: The information contained in this message or any attached 
document is confidential and intended only for individuals to whom it is 
addressed. If you got this message in error, please inform me immediately 
using one of the methods above. In some cases, I may ask you to return the 
documents at my expense. In general, please simply destroy the information 
at once. Any unauthorized use, distribution, or copying of this information 
is prohibited.

**Comment by erinzm** [comment]
Thanks ;) Do you want me to create a Vagrant or Docker container for our
dev enviroment? I can do that fairly easily.

**Comment by sphasse** [comment]
That would be very handy.  I've been meaning to play with Docker anyway,
but whichever you think is more appropriate would be great.

Thanks!

Scott

On Sat, Aug 30, 2014 at 9:08 PM, Liam M notifications@github.com wrote:

> Thanks ;) Do you want me to create a Vagrant or Docker container for our
> dev enviroment? I can do that fairly easily.
> 
> On Sat, Aug 30, 2014 at 9:01 PM, sphasse notifications@github.com
> wrote:
> 
> > Yes, as Tesseract is a native project you'll need to follow the
> > instructions to build it and import it as a library project. There is
> > already a (probably unresolved right now in your environment) reference
> > to
> > the tess-two project as a library project in the nsa-away project (in
> > eclipse, project->properties->Android) that might need to be changed
> > depending on the platform you are running on. The tess-two build
> > instructions can be found at https://github.com/rmtheis/tess-two, but
> > let
> > me know if you have any issues.
> > 
> > On Sat, Aug 30, 2014 at 8:45 PM, Liam M notifications@github.com
> > wrote:
> > 
> > > Yeah, thanks again @sphasse https://github.com/sphasse for the
> > > help.
> > > Now com.googlecode.tesseract.android.TessBaseAPI is failing to be
> > > imported in _nsa-away_. I have all the latest, do I need to download
> > > and
> > > install other jars?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/Sector67/nsa-away/issues/34#issuecomment-53975695.
> > 
> > ## 
> > 
> > http://flexion.us
> > Scott Hasse
> > Partner & CTO
> > _T._ 866-620-4353 _C._ 608-206-1813
> > _E._ shasse@flexion.us
> > FLEXION - VALUE FORWARD
> > 1500 West Main Street, Suite 500
> > Sun Prairie, WI 53590
> > https://www.facebook.com/pages/Flexion/261352600607280
> > http://twitter.com/#!/flexion1
> > https://plus.google.com/u/0/117487668359646793321/posts
> > 
> > ## 
> > 
> > ---
> > 
> > _Notice_: The information contained in this message or any attached
> > document is confidential and intended only for individuals to whom it is
> > addressed. If you got this message in error, please inform me
> > immediately
> > using one of the methods above. In some cases, I may ask you to return
> > the
> > documents at my expense. In general, please simply destroy the
> > information
> > at once. Any unauthorized use, distribution, or copying of this
> > information
> > is prohibited.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Sector67/nsa-away/issues/34#issuecomment-53975948.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Sector67/nsa-away/issues/34#issuecomment-53976054.

## 

 http://flexion.us
 Scott Hasse
Partner & CTO
_T._ 866-620-4353 _C._ 608-206-1813
_E._ shasse@flexion.us
 FLEXION - VALUE FORWARD
1500 West Main Street, Suite 500
Sun Prairie, WI 53590
 https://www.facebook.com/pages/Flexion/261352600607280
http://twitter.com/#!/flexion1
https://plus.google.com/u/0/117487668359646793321/posts

## 

---

_Notice_: The information contained in this message or any attached 
document is confidential and intended only for individuals to whom it is 
addressed. If you got this message in error, please inform me immediately 
using one of the methods above. In some cases, I may ask you to return the 
documents at my expense. In general, please simply destroy the information 
at once. Any unauthorized use, distribution, or copying of this information 
is prohibited.
