### ISSUE TITLE
OCR Functionality

### ISSUE THREAD

**Issue by pnovotnak** [Sector67/nsa-away#7]
Create a fragment to capture an image, view captured text

**Comment by pnovotnak** [comment]
![ocr](https://cloud.githubusercontent.com/assets/5713245/3491018/b38ea018-0583-11e4-9b1b-9945d50134fc.jpg)

**Comment by sphasse** [comment]
Superceded by #27 and #28

**Comment by erinzm** [comment]
#27 done, superceded by #28.
