### ISSUE TITLE
Input Selection Fragment

### ISSUE THREAD

**Issue by pnovotnak** [Sector67/nsa-away#9]
Fragment to allow manual input or opening the OCR capture fragment

**Comment by pnovotnak** [comment]
![select-input](https://cloud.githubusercontent.com/assets/5713245/3491026/e8aab2be-0583-11e4-9b37-1d9e44f3d0ee.jpg)

**Comment by erinzm** [comment]
Done (sort-of) via c1e1d9f1461c29183d426cf005a91ba793b07d66.
